[package]
name = "rasterizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openexr = "0.11.0"
eframe = "0.22.0"
half = "1.6.0"
rand = "0.8"